from django.urls import path

from .sso_views import (
    GoogleCallbackView,
    GoogleLoginView,
    MicrosoftCallbackView,
    MicrosoftLoginView,
    SSOStatusView,
)
from .views import (
    AdminAllowedIpDetailView,
    AdminAllowedIpsView,
    AdminAuditLogsCsvExportView,
    AdminAuditLogsView,
    AdminBackupView,
    AdminBiometricDeviceDetailView,
    AdminBiometricDevicesView,
    AdminCommandCenterView,
    AdminConsentLedgerView,
    AdminEmailTemplatesView,
    AdminEmployeesCsvExportView,
    AdminEmployeesCsvImportView,
    AdminFaceEnrollmentsView,
    AdminGdprDeleteView,
    AdminGdprExportView,
    AdminGeofenceDetailView,
    AdminGeofencesView,
    AdminHolidayDetailView,
    AdminHolidaysView,
    AdminLiveActivityView,
    AdminLoginRecordsView,
    AdminPushCampaignView,
    AdminRetentionPoliciesView,
    AdminSystemStatsView,
    AdminUserActionView,
    AdminUsersListView,
    AdminWebhookDetailView,
    AdminWebhooksView,
    AssetRequestView,
    AttendanceFaceVerifyPunchInView,
    AttendanceMonthlyView,
    AttendancePunchInView,
    AttendancePunchOutView,
    AttendanceRegularizeView,
    AttendanceTeamView,
    AttendanceTodayView,
    AttendanceWeeklyView,
    AuthView,
    AvatarUploadView,
    ChangePasswordView,
    ClaimSubmitView,
    DashboardAnalyticsView,
    DashboardAnnouncementsView,
    DashboardSummaryView,
    DepartmentsView,
    DeviceRegisterView,
    EmployeeDetailView,
    EmployeesListView,
    EmployeesSearchView,
    FeedbackCheckView,
    FeedbackSubmitView,
    FixReportingManagersView,
    ForgotPasswordView,
    LeaveApplyView,
    LeaveBalanceView,
    LeaveTypesListView,
    LogoutView,
    ManagerStatsView,
    MeHeartbeatView,
    MePresenceSettingsView,
    NotificationReadView,
    NotificationsReadAllView,
    NotificationsView,
    OrgChartView,
    PayslipHTMLView,
    PayslipPDFView,
    PayslipsListView,
    PayslipsView,
    PayslipWebDetailProxyView,
    PayslipWebProxyView,
    PresenceListView,
    RefreshTokenView,
    RequestAcceptView,
    RequestCancelView,
    RequestDetailView,
    RequestRejectView,
    RequestsListView,
    SettingsView,
    ShiftRequestView,
    ShiftsListView,
    TeamMemberActivityView,
    TeamMembersView,
    TicketRaiseView,
    UserMeView,
    WorkTypeRequestView,
    WorkTypesListView,
)

urlpatterns = [
    # Auth
    path('auth/login', AuthView.as_view(), name='login'),
    path('auth/refresh', RefreshTokenView.as_view(), name='token_refresh'),
    path('auth/logout', LogoutView.as_view(), name='logout'),
    path('auth/change-password', ChangePasswordView.as_view(), name='change_password'),
    path('auth/forgot-password', ForgotPasswordView.as_view(), name='forgot_password'),
    # SSO
    path('auth/microsoft/login', MicrosoftLoginView.as_view(), name='microsoft_login'),
    path('auth/microsoft/callback', MicrosoftCallbackView.as_view(), name='microsoft_callback'),
    path('auth/google/login', GoogleLoginView.as_view(), name='google_login'),
    path('auth/google/callback', GoogleCallbackView.as_view(), name='google_callback'),
    path('auth/sso/status', SSOStatusView.as_view(), name='sso_status'),
    # User
    path('users/me', UserMeView.as_view(), name='user_me'),
    path('users/me/avatar', AvatarUploadView.as_view(), name='avatar_upload'),
    # Attendance
    path('attendance/punch-in', AttendancePunchInView.as_view(), name='punch_in'),
    path('attendance/face-punch-in', AttendanceFaceVerifyPunchInView.as_view(), name='face_punch_in'),
    path('attendance/punch-out', AttendancePunchOutView.as_view(), name='punch_out'),
    path('attendance/today', AttendanceTodayView.as_view(), name='attendance_today'),
    path('attendance/monthly', AttendanceMonthlyView.as_view(), name='attendance_monthly'),
    path('attendance/weekly', AttendanceWeeklyView.as_view(), name='attendance_weekly'),
    path('attendance/team', AttendanceTeamView.as_view(), name='attendance_team'),
    path('attendance/regularize', AttendanceRegularizeView.as_view(), name='attendance_regularize'),
    path('attendance/update/<int:pk>', AttendanceRegularizeView.as_view(), name='attendance_update'),
    # Leaves
    path('leaves/balance', LeaveBalanceView.as_view(), name='leave_balance'),
    path('leaves/apply', LeaveApplyView.as_view(), name='leave_apply'),
    path('leaves/update/<int:pk>', LeaveApplyView.as_view(), name='leave_update'),
    # Claims
    path('claims/submit', ClaimSubmitView.as_view(), name='claim_submit'),
    path('claims/update/<int:pk>', ClaimSubmitView.as_view(), name='claim_update'),
    # Tickets
    path('tickets/raise', TicketRaiseView.as_view(), name='ticket_raise'),
    path('tickets/update/<int:pk>', TicketRaiseView.as_view(), name='ticket_update'),
    # Shift Requests
    path('shifts/request', ShiftRequestView.as_view(), name='shift_request'),
    path('shifts/update/<int:pk>', ShiftRequestView.as_view(), name='shift_update'),
    # Work Type Requests
    path('work-type/request', WorkTypeRequestView.as_view(), name='work_type_request'),
    path('work-type/update/<int:pk>', WorkTypeRequestView.as_view(), name='work_type_update'),
    # Asset Requests
    path('assets/request', AssetRequestView.as_view(), name='asset_request'),
    path('assets/update/<int:pk>', AssetRequestView.as_view(), name='asset_update'),
    # Requests
    path('requests', RequestsListView.as_view(), name='requests_list'),
    path('requests/<int:pk>', RequestDetailView.as_view(), name='request_detail'),
    path('requests/<int:pk>/accept', RequestAcceptView.as_view(), name='request_accept'),
    path('requests/<int:pk>/reject', RequestRejectView.as_view(), name='request_reject'),
    path('requests/<int:pk>/cancel', RequestCancelView.as_view(), name='request_cancel'),
    # Payslips
    path('payslips', PayslipsView.as_view(), name='payslips'),
    path('payslips/list', PayslipsListView.as_view(), name='payslips_list'),
    path('payslips/<int:pk>/pdf', PayslipPDFView.as_view(), name='payslip_pdf'),
    path('payslips/<int:pk>/html', PayslipHTMLView.as_view(), name='payslip_html'),
    # Web HRMS payslip proxy
    path('payslip/web/', PayslipWebProxyView.as_view(), name='payslip_web_list'),
    path('payslip/web/<int:pk>/', PayslipWebDetailProxyView.as_view(), name='payslip_web_detail'),
    # Notifications
    path('notifications', NotificationsView.as_view(), name='notifications'),
    path('notifications/<int:pk>/read', NotificationReadView.as_view(), name='notification_read'),
    path('notifications/read-all', NotificationsReadAllView.as_view(), name='notifications_read_all'),
    path('notifications/register-device', DeviceRegisterView.as_view(), name='device_register'),
    # Employees
    path('employees', EmployeesListView.as_view(), name='employees_list'),
    path('employees/search', EmployeesSearchView.as_view(), name='employees_search'),
    # Activity status (Round 5)
    path('me/heartbeat', MeHeartbeatView.as_view(), name='me_heartbeat'),
    path('me/presence-settings', MePresenceSettingsView.as_view(), name='me_presence_settings'),
    path('presence', PresenceListView.as_view(), name='presence_list'),
    path('employees/<int:pk>', EmployeeDetailView.as_view(), name='employee_detail'),
    # Dashboard
    path('dashboard/summary', DashboardSummaryView.as_view(), name='dashboard_summary'),
    path('dashboard/announcements', DashboardAnnouncementsView.as_view(), name='dashboard_announcements'),
    path('dashboard/analytics', DashboardAnalyticsView.as_view(), name='dashboard_analytics'),
    # Reference Data
    path('departments', DepartmentsView.as_view(), name='departments'),
    path('shifts', ShiftsListView.as_view(), name='shifts'),
    path('work-types', WorkTypesListView.as_view(), name='work_types'),
    path('leave-types', LeaveTypesListView.as_view(), name='leave_types'),
    # App Feedback
    path('feedback/check', FeedbackCheckView.as_view(), name='feedback_check'),
    path('feedback/submit', FeedbackSubmitView.as_view(), name='feedback_submit'),
    # Team Management
    path('team/members', TeamMembersView.as_view(), name='team_members'),
    path('team/members/<int:pk>/activity', TeamMemberActivityView.as_view(), name='team_member_activity'),
    # Manager Stats & Org Chart
    path('dashboard/manager-stats', ManagerStatsView.as_view(), name='manager_stats'),
    path('org-chart', OrgChartView.as_view(), name='org_chart'),
    path('admin/fix-reporting-managers', FixReportingManagersView.as_view(), name='fix_reporting_managers'),
    # Settings
    path('settings', SettingsView.as_view(), name='settings'),
    # Admin (super-admin only)
    path('admin/command-center', AdminCommandCenterView.as_view(), name='admin_command_center'),
    path('admin/audit-logs', AdminAuditLogsView.as_view(), name='admin_audit_logs'),
    path(
        'admin/audit-logs/export-csv',
        AdminAuditLogsCsvExportView.as_view(),
        name='admin_audit_logs_export_csv',
    ),
    path('admin/users', AdminUsersListView.as_view(), name='admin_users_list'),
    path('admin/users/<int:pk>/<str:action>', AdminUserActionView.as_view(), name='admin_user_action'),
    # Tier 2 — config + data ops
    path('admin/geofences', AdminGeofencesView.as_view(), name='admin_geofences'),
    path('admin/geofences/<int:pk>', AdminGeofenceDetailView.as_view(), name='admin_geofence_detail'),
    path('admin/holidays', AdminHolidaysView.as_view(), name='admin_holidays'),
    path('admin/holidays/<int:pk>', AdminHolidayDetailView.as_view(), name='admin_holiday_detail'),
    path('admin/email-templates', AdminEmailTemplatesView.as_view(), name='admin_email_templates'),
    path(
        'admin/employees/export-csv', AdminEmployeesCsvExportView.as_view(), name='admin_employees_export_csv'
    ),
    path(
        'admin/employees/import-csv', AdminEmployeesCsvImportView.as_view(), name='admin_employees_import_csv'
    ),
    path('admin/backup', AdminBackupView.as_view(), name='admin_backup'),
    # Tier 3
    path('admin/system-stats', AdminSystemStatsView.as_view(), name='admin_system_stats'),
    path('admin/live-activity', AdminLiveActivityView.as_view(), name='admin_live_activity'),
    path('admin/push-campaign', AdminPushCampaignView.as_view(), name='admin_push_campaign'),
    path('admin/face-enrollments', AdminFaceEnrollmentsView.as_view(), name='admin_face_enrollments'),
    path('admin/webhooks', AdminWebhooksView.as_view(), name='admin_webhooks'),
    path('admin/webhooks/<int:pk>', AdminWebhookDetailView.as_view(), name='admin_webhook_detail'),
    # Tier 4
    path('admin/users/<int:pk>/gdpr-export', AdminGdprExportView.as_view(), name='admin_gdpr_export'),
    path('admin/users/<int:pk>/gdpr-delete', AdminGdprDeleteView.as_view(), name='admin_gdpr_delete'),
    path('admin/retention-policies', AdminRetentionPoliciesView.as_view(), name='admin_retention'),
    path('admin/consent-ledger', AdminConsentLedgerView.as_view(), name='admin_consent_ledger'),
    # Round 4 — login telemetry + IP allowlist
    path('admin/allowed-ips', AdminAllowedIpsView.as_view(), name='admin_allowed_ips'),
    path('admin/allowed-ips/<int:pk>', AdminAllowedIpDetailView.as_view(), name='admin_allowed_ip_detail'),
    path('admin/login-records', AdminLoginRecordsView.as_view(), name='admin_login_records'),
    # Biometric device management
    path('admin/biometric-devices', AdminBiometricDevicesView.as_view(), name='admin_biometric_devices'),
    path(
        'admin/biometric-devices/<str:pk>',
        AdminBiometricDeviceDetailView.as_view(),
        name='admin_biometric_device_detail',
    ),
]
