name: hrms_demo
description: "PPulse HRMS Demo Application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  fl_chart: ^0.70.2
  provider: ^6.1.2
  flutter_animate: ^4.5.2
  intl: ^0.19.0
  pdfx: ^2.6.0
  flutter_local_notifications: ^21.0.0
  vibration: ^3.1.8
  http: ^1.2.0
  shared_preferences: ^2.2.2
  image_picker: ^1.2.1
  url_launcher: ^6.3.1
  path_provider: ^2.1.2
  live_activities: ^2.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sample.pdf
