# Generated by Django 6.0.3 on 2026-04-08 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_attendance_punch_in_device_attendance_punch_in_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerequest',
            name='attachment_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancerequest',
            name='attendance_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancerequest',
            name='shift_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
