# Generated by Django 6.0.3 on 2026-04-08 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_attendancerequest_attachment_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeFaceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('embedding', models.BinaryField(blank=True, null=True)),
                ('embedding_dim', models.IntegerField(default=512)),
                ('num_samples', models.IntegerField(default=0)),
                ('source_files', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'employee_face_data',
                'managed': True,
            },
        ),
    ]
