# Generated by Django 6.0.3 on 2026-04-10 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_employeefacedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_user_id', models.BigIntegerField(blank=True, null=True)),
                ('actor_name', models.TextField(blank=True, null=True)),
                ('actor_role', models.CharField(blank=True, max_length=20, null=True)),
                ('target_user_id', models.BigIntegerField(blank=True, null=True)),
                ('target_name', models.TextField(blank=True, null=True)),
                ('action', models.CharField(max_length=64)),
                ('target_type', models.CharField(blank=True, max_length=64, null=True)),
                ('target_id', models.CharField(blank=True, max_length=64, null=True)),
                ('payload', models.TextField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'api_audit_log',
                'managed': True,
                'indexes': [models.Index(fields=['-created_at'], name='api_audit_l_created_03b317_idx'), models.Index(fields=['action'], name='api_audit_l_action_6ec8ea_idx')],
            },
        ),
    ]
