# Generated by Django 6.0.3 on 2026-04-10 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_user_failed_login_count_user_locked_until_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField(help_text='Plain-text body. {{placeholder}} variables expanded by backend.')),
                ('html_body', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'api_email_template',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Geofence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('radius_meters', models.IntegerField(default=50)),
                ('is_office', models.BooleanField(default=True, help_text='Office geofence — blocks mobile punch-in inside it (must use biometric)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'api_geofence',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('holiday_date', models.DateField(db_index=True)),
                ('is_recurring', models.BooleanField(default=False, help_text='Repeats every year on this date')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'api_holiday',
                'ordering': ['holiday_date'],
                'managed': True,
            },
        ),
    ]
