# Generated by Django 6.0.3 on 2026-04-10 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_allowedip_loginrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestCc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(max_length=64)),
                ('request_id', models.BigIntegerField()),
                ('user_id', models.BigIntegerField(db_index=True)),
                ('user_name', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'api_request_cc',
                'managed': True,
                'indexes': [models.Index(fields=['request_type', 'request_id'], name='api_request_request_599379_idx')],
                'unique_together': {('request_type', 'request_id', 'user_id')},
            },
        ),
    ]
