# Generated by Django 6.0.3 on 2026-04-10 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_requestcc'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleTimesheetEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('activity_name', models.TextField(blank=True, default='')),
                ('hours', models.FloatField(default=0)),
                ('work_location', models.TextField(blank=True, default='wfo')),
                ('comments', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_by_id', models.BigIntegerField(blank=True, null=True)),
                ('modified_by_id', models.BigIntegerField(blank=True, null=True)),
                ('project_id', models.BigIntegerField(blank=True, null=True)),
                ('timesheet_period_id', models.BigIntegerField(blank=True, null=True)),
                ('timesheet_project_id', models.BigIntegerField(blank=True, null=True)),
                ('timesheet_task_id', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'simple_timesheet_entry',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SimpleTimesheetPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('status', models.TextField(default='draft')),
                ('total_hours', models.FloatField(default=0)),
                ('total_wfo_days', models.IntegerField(default=0)),
                ('total_wfh_days', models.IntegerField(default=0)),
                ('total_wfo_hours', models.FloatField(default=0)),
                ('total_wfh_hours', models.FloatField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('employee_id', models.BigIntegerField(blank=True, null=True)),
                ('created_by_id', models.BigIntegerField(blank=True, null=True)),
                ('modified_by_id', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('approved_by_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'simple_timesheet_period',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TimesheetProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('project_code', models.TextField(blank=True, null=True)),
                ('client_name', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_billable', models.BooleanField(default=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('company_id', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'timesheet_project',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TimesheetTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('task_code', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('project_id', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'timesheet_task',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserPresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(unique=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('push_enabled', models.BooleanField(default=True)),
                ('timesheet_reminders_enabled', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'api_user_presence',
                'managed': True,
            },
        ),
    ]
