# Generated by Django 6.0.3 on 2026-04-15 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_add_app_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='pay_head_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
