# Generated by Django 6.0.3 on 2026-05-04 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_geofence_has_biometric'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='punch_in_ip',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='punch_out_ip',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='geofence',
            name='is_office',
            field=models.BooleanField(default=True, help_text='Office geofence — if has_biometric is True, blocks mobile punch-in inside it'),
        ),
    ]
